"""core schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 12:36:48.225650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'system', 'staff', name='actortype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('purpose', sa.String(length=128), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_records')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_records_hash'))
    )
    op.create_index(op.f('ix_audit_records_event_type'), 'audit_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_records_scan_id'), 'audit_records', ['scan_id'], unique=False)
    op.create_index(op.f('ix_audit_records_subject_id'), 'audit_records', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('subjects',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('exclusion_state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_subjects_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('owner_user_id', name=op.f('uq_subjects_owner_user_id'))
    )
    op.create_table('identifiers',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('email', 'phone', 'username', 'full_name', 'city', name='identifierkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value_raw', sa.String(length=512), nullable=False),
    sa.Column('value_normalized', sa.String(length=512), nullable=False),
    sa.Column('verification_state', sa.Enum('unverified', 'pending', 'verified', name='verificationstate', native_enum=False, create_constraint=True, length=32), server_default='unverified', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_identifiers_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identifiers')),
    sa.UniqueConstraint('subject_id', 'kind', 'value_normalized', name='uq_identifier_seed')
    )
    op.create_index(op.f('ix_identifiers_subject_id'), 'identifiers', ['subject_id'], unique=False)
    op.create_table('scans',
    sa.Column('requester_user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('t0', name='scantier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'gated', 'running', 'resolving', 'scoring', 'done', 'failed', 'held', name='scanstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose = 'self'", name=op.f('ck_scans_purpose_self_only')),
    sa.CheckConstraint("tier = 't0'", name=op.f('ck_scans_tier_t0_only')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name=op.f('fk_scans_requester_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_scans_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index('ix_scans_requester_created', 'scans', ['requester_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scans_subject_id'), 'scans', ['subject_id'], unique=False)
    op.create_table('abuse_signals',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('velocity', 'minor_subject', 'victim_protection', 'anomaly', name='abusesignalkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warn', 'block', name='abusesignalseverity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewing', 'actioned', 'dismissed', name='abusesignalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_abuse_signals_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_abuse_signals_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abuse_signals'))
    )
    op.create_index(op.f('ix_abuse_signals_user_id'), 'abuse_signals', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('credential', 'broker', 'social', 'records', 'linkage', name='findingcategory', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sensitivity', sa.Enum('low', 'medium', 'high', 'critical', name='sensitivity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('exploitability', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('active', 'resolved', 'stale', 'suppressed', name='findingstate', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vault_ref', sa.String(length=128), nullable=True),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_findings_confidence_range')),
    sa.CheckConstraint('exploitability IS NULL OR (exploitability >= 0 AND exploitability <= 1)', name=op.f('ck_findings_exploitability_range')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_findings_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_findings_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('scan_id', 'dedupe_key', name='uq_finding_scan_dedupe')
    )
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_subject_id'), 'findings', ['subject_id'], unique=False)
    op.create_table('scores',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('subscores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('contributing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('overall >= 0 AND overall <= 100', name=op.f('ck_scores_overall_range')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scores_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_scores_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('scan_id', name='uq_score_scan')
    )
    op.create_index(op.f('ix_scores_subject_id'), 'scores', ['subject_id'], unique=False)
    op.create_table('remediation_tasks',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('opt_out', 'drop', 'dsar', 'hardening', name='remediationtype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'started', 'requested', 'acknowledged', 'removed', 'done', 'failed', 'relisted', name='remediationstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_score_impact', sa.Float(), nullable=True),
    sa.Column('realized_score_impact', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediation_tasks_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_remediation_tasks_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_tasks'))
    )
    op.create_index(op.f('ix_remediation_tasks_subject_id'), 'remediation_tasks', ['subject_id'], unique=False)
        # ── Audit immutability (FR-TS-1) ──────────────────────────────────
    # App-level rows are append-only: UPDATE/DELETE raise. TRUNCATE stays
    # owner-only (Postgres default) for maintenance/retention jobs; the
    # production app role is never the table owner.
    op.execute(
        """
        CREATE FUNCTION audit_records_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_records is append-only (FR-TS-1): % blocked', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_records_immutable
        BEFORE UPDATE OR DELETE ON audit_records
        FOR EACH ROW EXECUTE FUNCTION audit_records_immutable();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_tasks_subject_id'), table_name='remediation_tasks')
    op.drop_table('remediation_tasks')
    op.drop_index(op.f('ix_scores_subject_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_findings_subject_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_abuse_signals_user_id'), table_name='abuse_signals')
    op.drop_table('abuse_signals')
    op.drop_index(op.f('ix_scans_subject_id'), table_name='scans')
    op.drop_index('ix_scans_requester_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_identifiers_subject_id'), table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_records_subject_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_scan_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_event_type'), table_name='audit_records')
    op.drop_table('audit_records')
    op.execute("DROP TRIGGER IF EXISTS trg_audit_records_immutable ON audit_records")
    op.execute("DROP FUNCTION IF EXISTS audit_records_immutable()")
    # ### end Alembic commands ###
