"""finding identifier provenance

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-10 12:48:11.750870

"""
import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('identifier_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_findings_identifier_id'), 'findings', ['identifier_id'], unique=False)
    op.create_foreign_key(op.f('fk_findings_identifier_id_identifiers'), 'findings', 'identifiers', ['identifier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_findings_identifier_id_identifiers'), 'findings', type_='foreignkey')
    op.drop_index(op.f('ix_findings_identifier_id'), table_name='findings')
    op.drop_column('findings', 'identifier_id')
    # ### end Alembic commands ###
