"""tos acceptances

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-10 12:54:17.593943

"""
import sqlalchemy as sa
from alembic import op

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tos_acceptances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tos_acceptances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tos_acceptances')),
    sa.UniqueConstraint('user_id', 'version', name='uq_tos_user_version')
    )
    op.create_index(op.f('ix_tos_acceptances_user_id'), 'tos_acceptances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tos_acceptances_user_id'), table_name='tos_acceptances')
    op.drop_table('tos_acceptances')
    # ### end Alembic commands ###
