"""pii vault

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-10 13:29:09.678779

"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_items',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_vault_items_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_items'))
    )
    op.create_index(op.f('ix_vault_items_expires_at'), 'vault_items', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vault_items_subject_id'), 'vault_items', ['subject_id'], unique=False)
    op.create_table('vault_keys',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_vault_keys_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_keys')),
    sa.UniqueConstraint('subject_id', name=op.f('uq_vault_keys_subject_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_keys')
    op.drop_index(op.f('ix_vault_items_subject_id'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_expires_at'), table_name='vault_items')
    op.drop_table('vault_items')
    # ### end Alembic commands ###
