"""rate limit policies

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-10 13:30:55.619961

"""
import sqlalchemy as sa
from alembic import op

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_policies',
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scans_per_day', sa.Integer(), nullable=False),
    sa.Column('scan_burst', sa.Integer(), nullable=False),
    sa.Column('burst_window_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_policies')),
    sa.UniqueConstraint('scope', name=op.f('uq_rate_limit_policies_scope'))
    )

    # Seed the free-plan policy from the environment defaults so limits are
    # live-tunable (UPDATE this row — no deploy) from day one.
    import uuid as _uuid

    from ayin.config import get_settings as _gs

    _s = _gs()
    op.execute(
        sa.text(
            "INSERT INTO rate_limit_policies "
            "(id, scope, scans_per_day, scan_burst, burst_window_minutes) "
            "VALUES (CAST(:id AS uuid), 'free', :spd, :burst, 10)"
        ).bindparams(id=str(_uuid.uuid4()), spd=_s.rate_limit_scans_per_day,
                     burst=_s.rate_limit_burst)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_policies')
    # ### end Alembic commands ###
