"""resolution columns

Revision ID: 0008
Revises: 0007
Create Date: 2026-06-10 16:32:15.731619

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('match_status', sa.Enum('auto_matched', 'possible', 'confirmed', 'rejected', name='matchstatus', native_enum=False, create_constraint=True, length=32), server_default='possible', nullable=False))
    op.add_column('findings', sa.Column('match_confidence', sa.Float(), nullable=True))
    op.add_column('findings', sa.Column('corroboration_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('findings', sa.Column('duplicate_of', sa.Uuid(), nullable=True))
    op.add_column('findings', sa.Column('merged_sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('findings', sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_foreign_key(op.f('fk_findings_duplicate_of_findings'), 'findings', 'findings', ['duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_findings_duplicate_of_findings'), 'findings', type_='foreignkey')
    op.drop_column('findings', 'resolution')
    op.drop_column('findings', 'merged_sources')
    op.drop_column('findings', 'duplicate_of')
    op.drop_column('findings', 'corroboration_count')
    op.drop_column('findings', 'match_confidence')
    op.drop_column('findings', 'match_status')
    # ### end Alembic commands ###
