"""protection entries

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-11 01:47:42.078095

"""
import sqlalchemy as sa
from alembic import op

revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protection_entries',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protection_entries')),
    sa.UniqueConstraint('value_hash', name=op.f('uq_protection_entries_value_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protection_entries')
    # ### end Alembic commands ###
