"""exclusions

Revision ID: 0011
Revises: 0010
Create Date: 2026-06-11 01:52:12.642991

"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusions',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_exclusions_token_hash')),
    sa.UniqueConstraint('value_hash', name=op.f('uq_exclusions_value_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusions')
    # ### end Alembic commands ###
