"""analytics events

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-11 02:18:35.680520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_ref', sa.String(length=16), nullable=True),
    sa.Column('scan_ref', sa.String(length=36), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_name_created', 'analytics_events', ['name', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_name_created', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
