"""intent signals

Revision ID: 0013
Revises: 0012
Create Date: 2026-06-11 02:24:42.220618

"""
import sqlalchemy as sa
from alembic import op

revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_signals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('monitoring', 'removal', name='intentkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_intent_signals_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_intent_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intent_signals')),
    sa.UniqueConstraint('user_id', 'kind', name='uq_intent_user_kind')
    )
    op.create_index(op.f('ix_intent_signals_user_id'), 'intent_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_signals_user_id'), table_name='intent_signals')
    op.drop_table('intent_signals')
    # ### end Alembic commands ###
